version: 2.1
executors:
    node8:
        docker:
            - image: circleci/node:8

parameters:
  hello:
    type: boolean
    default: false

commands:
    callhello:
        steps:
            - run:
                name: Call HelloWorld
                command: |
                    curl \
                    --user ${API_TOKEN}: \
                    --header "Content-Type: application/json" \
                    --data "{\"parameters\": {\"hello\": true}, \"branch\": \"new_api_test\"}" \
                    --request POST "https://circleci.com/api/v2/project/github/kptdobe/circleci_bug_report/pipeline"

jobs:
    build:
        executor: node8
        working_directory: ~/repo

        steps:
            - callhello

    hello:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo

        steps:
            - run:
                name: HelloWorld
                command: echo "HelloWorld"

workflows:
    version: 2
    build:
        when: "[ ! << pipeline.parameters.hello >> ]"
        jobs:
            - build
    hello:
        when: << pipeline.parameters.hello >>
        jobs:
            - hello
