version: 2.0

jobs:
    build:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo

        steps:
            - run:
                name: Call HelloWorld
                command: |
                    curl \
                    --user ${API_TOKEN}: \
                    --header "Content-Type: application/json" \
                    --data "{\"build_parameters\": {\"CIRCLE_JOB\": \"hello\"}}" \
                    --request POST "https://circleci.com/api/v1.1/project/github/kptdobe/circleci_bug_report/tree/v2.0"

    hello:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo

        steps:
            - run:
                name: HelloWorld
                command: echo "HelloWorld"

workflows:
    version: 2
    build:
        jobs:
            - build
    hello:
        jobs:
            - hello
