version: 2.1
executors:
    node8:
        docker:
            - image: circleci/node:8

parameters:
  hello:
    type: boolean
    default: false
  object:
    type: String

commands:
    callhello:
        steps:
            - run:
                name: Call HelloWorld
                command: |
                    curl \
                    --user ${API_TOKEN}: \
                    --header "Content-Type: application/json" \
                    --data "{ \"parameters\": {\"object\": { \"p1\": \"v1\", \"p2\": \"v2\"}}, \"branch\": \"api-2-playground\", \"hello\": \"true\"}" \
                    --request POST "https://circleci.com/api/v2/project/github/kptdobe/circleci_bug_report/pipeline"

jobs:
    build:
        executor: node8
        working_directory: ~/repo

        steps:
            - callhello

    hello:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo

        steps:
            - run:
                name: Object parameter value
                command: echo "<< pipeline.parameters.object >>"

workflows:
    version: 2
    build:
        unless: << pipeline.parameters.hello >>
        jobs:
            - build
    hello:
        when: << pipeline.parameters.hello >>
        jobs:
            - hello
