version: 2.1
executors:
    node8:
        docker:
            - image: circleci/node:8

commands:
    callhello:
        steps:
        - run:
            name: Call HelloWorld
            command: |
                curl \
                --user ${API_TOKEN}: \
                --header "Content-Type: application/json" \
                --data "{\"build_parameters\": {\"CIRCLE_JOB\": \"hello\"}}" \
                --request POST "https://circleci.com/api/v1.1/project/github/kptdobe/circleci_bug_report/master"

jobs:
    build:
        executor: node8
        working_directory: ~/repo

        steps:
        - callhello

    hello:
        executor: node8
        working_directory: ~/repo

        steps:
        - run:
            name: Hello world
            command: echo "Hello World"

workflows:
    version: 2
    build:
        jobs:
            - build
    hello:
        jobs:
            - hello
